### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by m0t0r** [Igogrek/angular-typescript#54]
Hey Igor,

I am Vitaly, sorry haven't found any other way to connect. I saw your article [How I stopped loving Angular](https://medium.com/@igogrek/how-i-stopped-loving-angular-c2935f7378c4). I see you got many questions and also many misconceptions. I've got pretty solid experience with Angular. We have built a couple of mid-size apps and just started building a huge one. We are feeling pretty good so far. If you wanna chat, let me know. If I can, I would be happy to help you to possibly be happy with Angular :)

**Comment by igogrek** [comment]
Hi. Please reach out in comments to article instead.
Thanks for the info, but I've worked with Angular for quite some time now, and for now I think nothing can make me happy abbout it (soon at least).
